Repository goostengine/goost, pull requests merged in 2020-12, with the labels that each got.

#39 Add boolean operator nodes in 2D (CSG)
  core/math/2d/geometry/goost_geometry_2d.cpp
  core/math/2d/geometry/goost_geometry_2d.h
  core/math/2d/geometry/goost_geometry_2d_bind.cpp
  core/math/2d/geometry/goost_geometry_2d_bind.h
  core/math/2d/geometry/poly/boolean/clipper10/poly_boolean_clipper10.cpp
  core/math/2d/geometry/poly/boolean/clipper10/poly_boolean_clipper10.h
  core/math/2d/geometry/poly/boolean/clipper6/poly_boolean_clipper6.cpp
  core/math/2d/geometry/poly/boolean/clipper6/poly_boolean_clipper6.h
  core/math/2d/geometry/poly/boolean/poly_boolean.cpp
  core/math/2d/geometry/poly/boolean/poly_boolean.h
  core/math/2d/geometry/poly/poly_node_2d.cpp
  core/math/2d/geometry/poly/poly_node_2d.h
  doc/GoostGeometry2D.xml
  doc/PolyCircle2D.xml
  doc/PolyCollisionShape2D.xml
  doc/PolyNode2D.xml
  doc/PolyRectangle2D.xml
  doc/PolyShape2D.xml
  editor/icons/icon_poly_circle_2d.svg
  editor/icons/icon_poly_collision_shape_2d.svg
  editor/icons/icon_poly_node_2d.svg
  editor/icons/icon_poly_rectangle_2d.svg
  editor/icons/icon_poly_shape_2d.svg
  editor/icons/source/poly_node_2d_template.svg
  goost.py
  scene/2d/SCsub
  scene/2d/editor/poly_node_2d_editor_plugin.cpp
  scene/2d/editor/poly_node_2d_editor_plugin.h
  scene/2d/editor/visual_shape_2d_editor_plugin.cpp
  scene/2d/poly_collision_shape_2d.cpp
  scene/2d/poly_collision_shape_2d.h
  scene/2d/poly_generators_2d.cpp
  scene/2d/poly_generators_2d.h
  scene/2d/poly_shape_2d.cpp
  scene/2d/poly_shape_2d.h
  scene/register_scene_types.cpp
  tests/README.md
  tests/project/addons/gut/comparator.gd
  tests/project/addons/gut/compare_result.gd
  tests/project/addons/gut/diff_formatter.gd
  tests/project/addons/gut/diff_tool.gd
  tests/project/addons/gut/gut.gd
  tests/project/addons/gut/plugin.cfg
  tests/project/addons/gut/spy.gd
  tests/project/addons/gut/strutils.gd
  tests/project/addons/gut/summary.gd
  tests/project/addons/gut/test.gd
  tests/project/addons/gut/test_collector.gd
  tests/project/addons/gut/utils.gd
  tests/project/goost/core/math/2d/geometry/poly/test_poly_boolean.gd
  tests/project/goost/core/math/2d/geometry/poly/test_poly_generators_2d.gd
  tests/project/goost/core/math/2d/geometry/poly/test_poly_node_2d.gd
  tests/project/goost/core/math/2d/geometry/poly/test_poly_shape_2d.gd
  tests/project/goost/core/math/2d/geometry/test_geometry_2d.gd
  tests/project/goost/core/math/test_random_2d.gd
  tests/project/goost/core/types/test_list.gd
Labels: breaks compat, enhancement, feature

#43 Add `GradientTexture2D`
  AUTHORS.md
  doc/GradientTexture2D.xml
  editor/icons/icon_gradient_texture_2d.svg
  goost.py
  scene/SCsub
  scene/register_scene_types.cpp
  scene/resources/gradient_texture_2d.cpp
  scene/resources/gradient_texture_2d.h
  tests/project/goost/scene/resources/test_gradient_texture_2d.gd
Labels: feature

#44 New icon for GradientTexture2D
  editor/icons/icon_gradient_texture_2d.svg
Labels: enhancement

#45 Add `Grid2D` structure to hold `Variant` values in 2D
  core/register_core_types.cpp
  core/types/grid_2d.cpp
  core/types/grid_2d.h
  doc/Grid2D.xml
  editor/icons/icon_grid_2d.svg
  goost.py
  tests/project/goost/core/types/test_grid_2d.gd
Labels: feature
